title: Salencore
description: Специалист информационной безопасности и эксперт по Vulnerability Management
url: "https://salencore.github.io"
baseurl: ""
lang: ru

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
